apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scaleml.name" . }}-pvc
  labels:
    app: {{ include "scaleml.name" . }}-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
