# Source: scaleml/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scaleml-pvc
  labels:
    app: scaleml-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi